volumes:
  meal_mingle:
    external: true
services:
  fastapi:
    environment:
      SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da
      WAIT_HOSTS: postgres:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://admin:password@postgres/meal_mingle
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - meal_mingle:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: meal_mingle
    ports:
      - "15432:5432"
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
      WATCHPACK_POLLING: true
